### ISSUE TITLE
Potential duplicate phrase and erroneous article

### ISSUE THREAD

**Issue by solt87** [standardebooks/arthur-conan-doyle_the-return-of-sherlock-holmes#1]
I might be wrong, but there may be two issues with the line referenced.

1. Shouldn't `He swaggered up a path as if[...]` be `He swaggered up the path as if [...]`? The context would warrant a definite article.
2. In the same sentence, `as if` is duplicated; is this how it is in the original, or is it an error?

https://github.com/standardebooks/arthur-conan-doyle_the-return-of-sherlock-holmes/blob/d923c85d2a318db615ed3560c2d25f01e05508dc/src/epub/text/the-adventure-of-the-dancing-men.xhtml#L217

**Comment by acabal** [comment]
Thanks, these should be fixed now!
