### ISSUE TITLE
Missing article

### ISSUE THREAD

**Issue by solt87** [standardebooks/arthur-conan-doyle_the-return-of-sherlock-holmes#2]
I do believe that `With bow` should be `With a bow`; that's also how it appears in
a printing referenced by [Wikisource](https://en.wikisource.org/wiki/Page%3AThe_Return_of_Sherlock_Holmes%2C_edition_published_in_1905_by_McClure%2C_Phillips_%26_Co.%2C_New_York..djvu/215).

https://github.com/standardebooks/arthur-conan-doyle_the-return-of-sherlock-holmes/blob/ed52bea05007fde910f712bd84a806c4c85244da/src/epub/text/the-adventure-of-charles-augustus-milverton.xhtml#L62

**Comment by acabal** [comment]
Thanks, this should be fixed now!
